### ISSUE TITLE
There is no Russian translation

### ISSUE THREAD

**Issue by wolfzerd** [GregorBiswanger/rxjs-fruits#14]
Hello Gregor! I see you made support for the Russian language, but I do not see Json with a Russian translation. Maybe you forgot to add it? Also, json with a Russian translation is not present either in pull requests, or in your commits :(
![image](https://user-images.githubusercontent.com/25350570/82426206-3c8c0980-9a90-11ea-8181-691b505b5e35.png)

**Comment by gregor-doroschenko** [comment]
Hey @ValentinChernyshov, I have been working on the Russian translation and I will add it within the next days.

**Comment by Cobr3n** [comment]
helo what about this ?

**Comment by wolfzerd** [comment]
> Hey @ValentinChernyshov, I have been working on the Russian translation and I will add it within the next days.

@gregor-doroschenko , if you want, I can help you. Just ask me)

**Comment by gregor-doroschenko** [comment]
@ValentinChernyshov Hey, sorry about the late reply. I had to go to the hospital for a few days and so I was unable to finish and to add my translation. I already saw that you made a pull request.

**Comment by wolfzerd** [comment]
> @ValentinChernyshov Hey, sorry about the late reply. I had to go to the hospital for a few days and so I was unable to finish and to add my translation. I already saw that you made a pull request.

@gregor-doroschenko ,  I hope you feel good.
Look at my PR, if you have any comments or suggestions - write a comment there)

**Comment by GregorBiswanger** [comment]
Thank you for your help! The game is now released in your language :)
