### ISSUE TITLE
The given dataset for the 'skipLast, skip & merge' exercise might cause confusion

### ISSUE THREAD

**Issue by RubenVermeulen** [GregorBiswanger/rxjs-fruits#22]
Hi @GregorBiswanger 

Really enjoy how low-level the learning experience can be for RxJS.

I noticed that exercise 14 ([skipLast, skip & merge](https://www.rxjs-fruits.com/skiplast-skip-merge)) can cause confusion. Let me explain.

It is expected to only have 3 apples left after using either `skipLast` or `skip`. The usable apples are the clean and dirty ones. If we take a closer look at the array it's clear that there are more than 3 items valid. The first 3 items and the last item are valid.

`const apples = from(['apple', 'dirty-apple', 'apple', 'old-apple', 'apple']);`

It looks to me that the last item in the list must be and `old` apple as well. That would make sense looking at the operators we are allowed to use.

Regards
Ruben

**Comment by GregorBiswanger** [comment]
I merged your PR.. Thanks! :)
