### ISSUE TITLE
Issue with level 15

### ISSUE THREAD

**Issue by Troy96** [GregorBiswanger/rxjs-fruits#25]
Hi @GregorBiswanger 

I was going through the Rxjs fruits game and very much enjoyed it while understanding it at the same time. But I seemed to have stuck at the level 15 wherein I can't figure out how to use the concatMap inside the pipe. Can you please help me with that?

Thanks

**Comment by Alfhir** [comment]
Hi, for the solution you might want to look at

https://github.com/GregorBiswanger/rxjs-fruits/blob/18c4e3dd655cba1c9cad6a5ec2f8cd8f0aa93ff6/cypress/integration/15_zip_concatmap.spec.ts#L20

**Comment by Troy96** [comment]
Yeah, it got resolved. Thank you :)
